name: Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Pull pyinstaller source
        run: git clone https://github.com/pyinstaller/pyinstaller

      - name: Compile pyinstaller
        run: pip install .\pyinstaller

      - name: Verify pyinstaller installation
        run: pyinstaller --version

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Create executable
        run: pyinstaller --onedir --hidden-import=pygame --add-data ".\LunarLander\assets;assets" --noconsole .\LunarLander\LunarLander.py

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: LunarLander
          path: .\dist\LunarLander
