name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Create Executable
        run: pyinstaller --onefile --hidden-import=pygame --add-data "./LunarLander/assets:assets" --add-data "./LunarLander/functions:functions" --noconsole ./LunarLander/LunarLander.py

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: LunarLander.exe
          path: ./dist/LunarLander.exe
